import nex
import sys
import os

doc=nex.GetActiveDocument()
nex.DecimateContVar(doc, "Down1",  doc["chan1"], 5)
nex.DecimateContVar(doc, "Down10", doc["chan10"], 5)
nex.DecimateContVar(doc, "Down11", doc["chan11"], 5)
nex.DecimateContVar(doc, "Down12", doc["chan12"], 5)
nex.DecimateContVar(doc, "Down13", doc["chan13"], 5)
nex.DecimateContVar(doc, "Down14", doc["chan14"], 5)
nex.DecimateContVar(doc, "Down15", doc["chan15"], 5)
nex.DecimateContVar(doc, "Down16", doc["chan16"], 5)
nex.DecimateContVar(doc, "Down17", doc["chan17"], 5)
nex.DecimateContVar(doc, "Down18", doc["chan18"], 5)
nex.DecimateContVar(doc, "Down19", doc["chan19"], 5)
nex.DecimateContVar(doc, "Down2", doc["chan2"], 5)
nex.DecimateContVar(doc, "Down20", doc["chan20"], 5)
nex.DecimateContVar(doc, "Down21", doc["chan21"], 5)
nex.DecimateContVar(doc, "Down22", doc["chan22"], 5)
nex.DecimateContVar(doc, "Down23", doc["chan23"], 5)
nex.DecimateContVar(doc, "Down24", doc["chan24"], 5)
nex.DecimateContVar(doc, "Down25", doc["chan25"], 5)
nex.DecimateContVar(doc, "Down26", doc["chan26"], 5)
nex.DecimateContVar(doc, "Down27", doc["chan27"], 5)
nex.DecimateContVar(doc, "Down28", doc["chan28"], 5)
nex.DecimateContVar(doc, "Down29", doc["chan29"], 5)
nex.DecimateContVar(doc, "Down3", doc["chan3"], 5)
nex.DecimateContVar(doc, "Down30", doc["chan30"], 5)
nex.DecimateContVar(doc, "Down31", doc["chan31"], 5)
nex.DecimateContVar(doc, "Down32", doc["chan32"], 5)
nex.DecimateContVar(doc, "Down4", doc["chan4"], 5)
nex.DecimateContVar(doc, "Down5", doc["chan5"], 5)
nex.DecimateContVar(doc, "Down6", doc["chan6"], 5)
nex.DecimateContVar(doc, "Down7", doc["chan7"], 5)
nex.DecimateContVar(doc, "Down8", doc["chan8"], 5)
nex.DecimateContVar(doc, "Down9", doc["chan9"], 5)
