import nex
import sys
import os

doc["1nonripple"] = IntOpposite(doc, doc["1interval"])
#doc["2nonripple"] = IntOpposite(doc, doc["2interval"])
doc["3nonripple"] = IntOpposite(doc, doc["3interval"])
#doc["4nonripple"] = IntOpposite(doc, doc["4interval"])
doc["5nonripple"] = IntOpposite(doc, doc["5interval"])
#doc["6nonripple"] = IntOpposite(doc, doc["6interval"])
doc["7nonripple"] = IntOpposite(doc, doc["7interval"])
#doc["8nonripple"] = IntOpposite(doc, doc["8interval"])
doc["9nonripple"] = IntOpposite(doc, doc["9interval"])
doc["10nonripple"] = IntOpposite(doc, doc["10interval"])
doc["11nonripple"] = IntOpposite(doc, doc["11interval"])
doc["12nonripple"] = IntOpposite(doc, doc["12interval"])
doc["13nonripple"] = IntOpposite(doc, doc["13interval"])
doc["14nonripple"] = IntOpposite(doc, doc["14interval"])
doc["15nonripple"] = IntOpposite(doc, doc["15interval"])
doc["16nonripple"] = IntOpposite(doc, doc["16interval"])
doc["17nonripple"] = IntOpposite(doc, doc["17interval"])
doc["18nonripple"] = IntOpposite(doc, doc["18interval"])
doc["19nonripple"] = IntOpposite(doc, doc["19interval"])
doc["20nonripple"] = IntOpposite(doc, doc["20interval"])
doc["21nonripple"] = IntOpposite(doc, doc["21interval"])
doc["22nonripple"] = IntOpposite(doc, doc["22interval"])
doc["23nonripple"] = IntOpposite(doc, doc["23interval"])
doc["24nonripple"] = IntOpposite(doc, doc["24interval"])
#doc["25nonripple"] = IntOpposite(doc, doc["25interval"])
doc["26nonripple"] = IntOpposite(doc, doc["26interval"])
#doc["27nonripple"] = IntOpposite(doc, doc["27interval"])
doc["28nonripple"] = IntOpposite(doc, doc["28interval"])
#doc["29nonripple"] = IntOpposite(doc, doc["29interval"])
doc["30nonripple"] = IntOpposite(doc, doc["30interval"])
#doc["31nonripple"] = IntOpposite(doc, doc["31interval"])
doc["32nonripple"] = IntOpposite(doc, doc["32interval"])

