import nex
import sys
import os

nex.ExecuteMenuCommand('WindowDynamic|Activate Z:\jbroussard\Hippocampal Study\ShamHipp3_7_3\Concatenated\ShamHipp3_7_3_2.nex5 [Graphs1]')
nex.SelectVariables(nex.GetActiveDocument(),'chan1')
nex.ApplyTemplate(nex.GetActiveDocument(),'RipplePSD1.ntp')
nex.SelectVariables(nex.GetActiveDocument(),'chan2')
nex.ApplyTemplate(nex.GetActiveDocument(),'RipplePSD2.ntp')
nex.SelectVariables(nex.GetActiveDocument(),'chan3')
nex.SelectVariables(nex.GetActiveDocument(),'chan4')
nex.SelectVariables(nex.GetActiveDocument(),'chan5')
nex.SelectVariables(nex.GetActiveDocument(),'chan6')
nex.SelectVariables(nex.GetActiveDocument(),'chan7')
nex.SelectVariables(nex.GetActiveDocument(),'chan8')
nex.SelectVariables(nex.GetActiveDocument(),'chan9')
nex.SelectVariables(nex.GetActiveDocument(),'chan10')
nex.SelectVariables(nex.GetActiveDocument(),'chan11')
nex.SelectVariables(nex.GetActiveDocument(),'chan12')
nex.SelectVariables(nex.GetActiveDocument(),'chan13')
nex.SelectVariables(nex.GetActiveDocument(),'chan14')
nex.SelectVariables(nex.GetActiveDocument(),'chan15')
nex.SelectVariables(nex.GetActiveDocument(),'chan16')
nex.SelectVariables(nex.GetActiveDocument(),'chan17')
nex.SelectVariables(nex.GetActiveDocument(),'chan18')
nex.SelectVariables(nex.GetActiveDocument(),'chan19')
nex.SelectVariables(nex.GetActiveDocument(),'chan20')
nex.SelectVariables(nex.GetActiveDocument(),'chan21')
nex.SelectVariables(nex.GetActiveDocument(),'chan22')
nex.SelectVariables(nex.GetActiveDocument(),'chan23')
nex.SelectVariables(nex.GetActiveDocument(),'chan24')
nex.SelectVariables(nex.GetActiveDocument(),'chan25')
nex.SelectVariables(nex.GetActiveDocument(),'chan26')
nex.SelectVariables(nex.GetActiveDocument(),'chan27')
nex.SelectVariables(nex.GetActiveDocument(),'chan28')
nex.SelectVariables(nex.GetActiveDocument(),'chan29')
nex.SelectVariables(nex.GetActiveDocument(),'chan30')
nex.SelectVariables(nex.GetActiveDocument(),'chan31')
nex.SelectVariables(nex.GetActiveDocument(),'chan32')
